libName: Anc81BC_

barcodeDict:
    'B1_ACG': 0
    'B1_AGC': 1
    'B2_AAA': 0
    'B2_AGA': 1
    'B3_AAC': 0
    'B3_AGT': 1
    'B4_AGC': 0
    'B4_CAC': 1
    'B5_AAG': 0
    'B5_AGA': 1
    'B6_CAG': 0
    'B6_GAG': 1
    'B7_CAG': 0
    'B7_CGG': 1
    'B8_ACG': 0
    'B8_GAG': 1
    'B9_AGC': 0
    'B9_GAC': 1
    'B10_CTT': 0
    'B10_TAC': 1
    'B11_AGC': 0
    'B11_GAC': 1
    'B12_AAC': 0
    'B12_AGT': 1
    'B13_ATC': 0
    'B13_GTG': 1
    'B14_AGC': 0
    'B14_GCA': 1
    'B15_ACC': 0
    'B15_AGT': 1

barcodeArray:
    - 'B1'
    - 'B2'
    - 'B3'
    - 'B4'
    - 'B5'
    - 'B6'
    - 'B7'
    - 'B8'
    - 'B9'
    - 'B10'
    - 'B11'
    - 'B12'
    - 'B13'
    - 'B14'
    - 'B15'

barcodeIndices:
    'B15': 0
    'B14': 7
    'B13': 14
    'B12': 21
    'B11': 28 
    'B10': 31
    'B9': 38
    'B8': 45
    'B7': 48
    'B6': 55
    'B5': 58
    'B4': 65
    'B3': 68 
    'B2': 75
    'B1': 78

libSize: 32768