libName: Anc82BC_

barcodeDict:
    'B1_ACG': 0
    'B1_AGC': 1
    'B2_AAA': 0
    'B2_AGA': 1
    'B3_AAC': 0
    'B3_AGC': 1

barcodeArray:
    - 'B1'
    - 'B2'
    - 'B3'

barcodeIndices:
    'B3': 0
    'B2': 7
    'B1': 14

libSize: 8